language: csharp
dist: trusty
os: linux
mono: none
dotnet: 2.1
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test Float.xAPI.Tests/Float.xAPI.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_success:
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "./Float.xAPI.Tests/coverage.opencover.xml" -t $CODECOV_TOKEN

branches:
  only:
    - master

git:
  depth: 1

sudo: false
