language: csharp
dist: trusty
os: linux
mono: none
dotnet: 2.1
install:
  - dotnet tool install fake-cli -g
script:
  - fake build
#  - dotnet nuget push Float.xAPI/bin/Release/*.nupkg -k $NUGET_KEY -s $NUGET_SOURCE
after_success:
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "./Float.xAPI.Tests/coverage.opencover.xml" -t $CODECOV_TOKEN

branches:
  only:
    - master

git:
  depth: 1

sudo: false
