language: csharp
dist: trusty
os: linux
mono: none
dotnet: 2.1
install:
  - dotnet restore
script:
  - dotnet build Float.xAPI/Float.xAPI.fsproj
  - dotnet test Float.xAPI.Tests/Float.xAPI.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_success:
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "./Float.xAPI.Tests/coverage.opencover.xml" -t $CODECOV_TOKEN
before_deploy:
  - sh create_release.sh
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "./Float.xAPI/bin/Release/*.nupkg"
  body: $(cat release_notes.md)
  skip_cleanup: true
  on:
    tags: true

branches:
  only:
    - master

git:
  depth: 1

sudo: false
